"""The scout answers from git and the tree, deterministically, and says when a
named file does not exist yet."""

import subprocess
import time

from inference_grid.lanes.scout import (
    latest_reports,
    module_names,
    orient,
    recent_commits,
    referencing_tests,
)


def git(repo, *args):
    subprocess.run(["git", "-C", str(repo), *args], check=True, capture_output=True)


def commit(repo, message, trailer=None):
    args = ["commit", "-q", "-m", message]
    if trailer:
        args += ["-m", trailer]
    git(repo, "-c", "user.name=Dev", "-c", "user.email=dev@example.com", *args)


def scouted_repo(tmp_path):
    repo = tmp_path / "repo"
    (repo / "src/pkg").mkdir(parents=True)
    (repo / "tests").mkdir()
    (repo / "docs/reports").mkdir(parents=True)
    git(repo, "init", "-q", "-b", "main")
    (repo / "src/pkg/recovery.py").write_text("def alarm(): return 1\n")
    (repo / "tests/test_recovery_alarm.py").write_text("from pkg.recovery import alarm\n")
    (repo / "tests/test_other.py").write_text("x = 1\n")
    git(repo, "add", "-A")
    commit(repo, "add recovery")
    (repo / "src/pkg/recovery.py").write_text("def alarm(): return 2\n")
    git(repo, "add", "-A")
    commit(repo, "alarm returns two", "Co-Authored-By: GLM-5.3-Flash <noreply@z.ai>")
    (repo / "docs/reports/glm-2026-09-13.md").write_text("old\n")
    time.sleep(0.02)
    (repo / "docs/reports/glm-2026-09-14.md").write_text("new\n")
    git(repo, "add", "-A")
    commit(repo, "reports")
    return repo


def test_recent_commits_are_newest_first_with_the_coauthor(tmp_path):
    repo = scouted_repo(tmp_path)
    rows = recent_commits(repo, ["src/pkg/recovery.py"])
    assert [r["subject"] for r in rows] == ["alarm returns two", "add recovery"]
    assert rows[0]["coauthor"].startswith("GLM-5.3-Flash") and rows[1]["coauthor"] == ""


def test_referencing_tests_match_on_module_name_only(tmp_path):
    repo = scouted_repo(tmp_path)
    assert module_names(["src/pkg/recovery.py", "frontend/src/app/pages/Rules.tsx", "a/__init__.py"]) == [
        "recovery", "Rules"]
    assert referencing_tests(repo, ["src/pkg/recovery.py"]) == ["tests/test_recovery_alarm.py"]
    assert referencing_tests(repo, ["src/pkg/__init__.py"]) == []


def test_latest_reports_are_newest_first(tmp_path):
    repo = scouted_repo(tmp_path)
    assert latest_reports(repo)[0] == "docs/reports/glm-2026-09-14.md"
    assert latest_reports(repo, "docs/nowhere") == []


def test_orient_renders_every_section_and_flags_an_absent_file(tmp_path):
    repo = scouted_repo(tmp_path)
    text = orient(repo, ["src/pkg/recovery.py", "src/pkg/attachments.py"])
    assert text.startswith("## Orientation (generated by the scout at ")
    assert "`src/pkg/recovery.py` — exists" in text
    assert "`src/pkg/attachments.py` — ABSENT (you will be creating it)" in text
    assert "alarm returns two [Co-Authored-By: GLM-5.3-Flash" not in text  # valueonly trailer
    assert "alarm returns two [GLM-5.3-Flash <noreply@z.ai>]" in text
    assert "`tests/test_recovery_alarm.py`" in text and "test_other" not in text
    assert "`docs/reports/glm-2026-09-14.md`" in text
    assert text == orient(repo, ["src/pkg/recovery.py", "src/pkg/attachments.py"])  # deterministic
