"""The scout node: orientation for a packet, produced by code, not by a model.

Before a brief is written, someone has to establish what is already there —
which commits last touched the files, which tests pin them, what the previous
lane reported. Until now that was the operator reading the tree by hand and
typing it into the brief. Every one of those facts is a query against git and
the filesystem, so this runs them and renders the answer as a section the
brief can carry verbatim. It never reads outside the repository and never
runs anything but `git`.
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence


def _git(repo: Path, *args: str) -> str:
    proc = subprocess.run(["git", "-C", str(repo), *args], capture_output=True, text=True)
    return proc.stdout if proc.returncode == 0 else ""


def recent_commits(repo: Path, paths: Sequence[str], limit: int = 8) -> List[Dict[str, str]]:
    """Newest commits touching any of `paths`: hash, date, subject, author-family trailer."""
    out = _git(repo, "log", f"-{limit}", "--date=short", "--format=%h%x1f%ad%x1f%s%x1f%(trailers:key=Co-Authored-By,valueonly)",
               "--", *paths)
    rows = []
    for line in out.splitlines():
        parts = line.split("\x1f")
        if len(parts) < 3:
            continue
        rows.append({"hash": parts[0], "date": parts[1], "subject": parts[2],
                     "coauthor": (parts[3] if len(parts) > 3 else "").strip().splitlines()[0]
                     if len(parts) > 3 and parts[3].strip() else ""})
    return rows


def module_names(paths: Iterable[str]) -> List[str]:
    """`src/pkg/a/b.py` → `b`, `frontend/src/app/pages/Rules.tsx` → `Rules`."""
    names = []
    for p in paths:
        stem = Path(p).stem
        if stem and stem not in ("__init__", "index") and stem not in names:
            names.append(stem)
    return names


def referencing_tests(repo: Path, paths: Sequence[str], test_roots: Sequence[str] = ("tests",),
                      limit: int = 20) -> List[str]:
    """Test files that mention any module name of `paths` (grep, tracked files only)."""
    names = module_names(paths)
    if not names:
        return []
    pattern = "|".join(re.escape(n) for n in names)
    out = _git(repo, "grep", "-l", "-E", pattern, "--", *[f"{r}/" for r in test_roots])
    return sorted(set(out.splitlines()))[:limit]


def latest_reports(repo: Path, reports_dir: str = "docs/reports", limit: int = 3) -> List[str]:
    root = repo / reports_dir
    if not root.is_dir():
        return []
    files = sorted((p for p in root.glob("*.md") if p.is_file()), key=lambda p: p.stat().st_mtime,
                   reverse=True)
    return [str(p.relative_to(repo)) for p in files[:limit]]


def existing_paths(repo: Path, paths: Sequence[str]) -> Dict[str, bool]:
    return {p: (repo / p).exists() for p in paths}


def orient(repo: Path, paths: Sequence[str], *, reports_dir: str = "docs/reports",
           test_roots: Sequence[str] = ("tests",), head: Optional[str] = None) -> str:
    """The orientation section, as markdown. Deterministic for a given tree."""
    repo = Path(repo)
    head = head or _git(repo, "rev-parse", "--short", "HEAD").strip()
    lines = [f"## Orientation (generated by the scout at {head})", ""]
    present = existing_paths(repo, paths)
    lines.append("Files this packet names, and whether they exist at this commit:")
    for p, ok in present.items():
        lines.append(f"- `{p}` — {'exists' if ok else 'ABSENT (you will be creating it)'}")
    commits = recent_commits(repo, [p for p, ok in present.items() if ok])
    lines += ["", "Most recent commits touching them (newest first) — read these before changing anything:"]
    if commits:
        for c in commits:
            who = f" [{c['coauthor']}]" if c["coauthor"] else ""
            lines.append(f"- `{c['hash']}` {c['date']} {c['subject']}{who}")
    else:
        lines.append("- none: these files have no history at this commit")
    tests = referencing_tests(repo, paths, test_roots)
    lines += ["", "Test files that reference these modules — they pin current behaviour and must keep passing:"]
    lines += [f"- `{t}`" for t in tests] or ["- none found by name; search before assuming there are none"]
    reports = latest_reports(repo, reports_dir)
    lines += ["", "Newest lane reports (read the first one for the format and for what was just done):"]
    lines += [f"- `{r}`" for r in reports] or ["- none"]
    return "\n".join(lines) + "\n"
